In [1]:
import numpy as np
import pandas as pd

In [17]:
from setup import get_data
from binarized import get_binarized
from embeddings import get_embeddings

In [18]:
train, valid, test = get_data(6)

## concatenate all the metadata into one block

In [19]:
train.head(2)

ID  label                                          statement  \
0   2635.json      1  Says the Annies List political group supports ...   
1  10540.json      3  When did the decline of coal start? It started...   

                              subject         speaker         speaker's job  \
0                            abortion    dwayne-bohac  State representative   
1  energy,history,job-accomplishments  scott-surovell        State delegate   

  state info  party  barely true counts  false counts  half true counts  \
0      Texas    1.0                   0             1                 0   
1   Virginia    0.0                   0             0                 1   

   mostly true counts  pants on fire counts            venue  lying ratio  \
0                   0                     0         a mailer          0.8   
1                   1                     0  a floor speech.          0.3   

   ratio significance  
0                0.01  
1                0.02

In [20]:
def get_numerical(col):
    a0 = np.array(train[col]).reshape(-1, 1)
    a1 = np.array(valid[col]).reshape(-1, 1)
    a2 = np.array( test[col]).reshape(-1, 1)
    return [a0, a1, a2]

In [21]:
def get_metadata():
    metadata = ([], [], []) #train, valid, test
    
    state   = get_binarized('state info')
    subject = get_binarized('subject')
    speaker = get_binarized('speaker', 500)
    
    job   = get_embeddings("speaker's job")
    venue = get_embeddings('venue')
    
    ratio = get_numerical('lying ratio')
    sig   = get_numerical('ratio significance')
    
    combined = [state, subject, speaker, job, venue, ratio, sig]
    
    print([i[0].shape for i in combined])
    meta_train = np.concatenate([i[0] for i in combined], axis=1)
    meta_valid = np.concatenate([i[1] for i in combined], axis=1)
    meta_test  = np.concatenate([i[2] for i in combined], axis=1)
  
    return meta_train, meta_valid, meta_test

In [22]:
meta_train, meta_valid, meta_test = get_metadata()

TypeError: get_binarized() missing 1 required positional argument: 'num_classes'

In [ ]:
meta_train.shape

In [9]:
meta_valid.shape

NameError: name 'meta_valid' is not defined

In [10]:
meta_test.shape

NameError: name 'meta_test' is not defined

In [11]:
a = np.arange(30)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
a[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [14]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])