In [2]:
from collections import Counter
import numpy as np
import math
from sklearn.preprocessing import MultiLabelBinarizer

from setup import get_train, get_valid, get_test

In [8]:
from subject import get_subject_train, get_classes
from setup import get_train, get_valid, get_test

In [4]:
#import from parents directory
import os, sys
sys.path.insert(1, os.path.join(sys.path[0], '..'))

import utils

In [5]:
#get pre-trained glove 
GLOVE_HOME = os.path.join('..','data', 'glove.6B')
glove = utils.glove2dict(os.path.join(GLOVE_HOME, 'glove.6B.50d.txt'))

In [9]:
train = get_train(6)
valid = get_valid(6)
test = get_test(6)

In [10]:
train.head(5)

ID  label                                          statement  \
0   2635.json      1  Says the Annies List political group supports ...   
1  10540.json      3  When did the decline of coal start? It started...   
2    324.json      4  Hillary Clinton agrees with John McCain "by vo...   
3   1123.json      1  Health care reform legislation is likely to ma...   
4   9028.json      3  The economic turnaround started at the end of ...   

                              subject         speaker         speaker's job  \
0                            abortion    dwayne-bohac  State representative   
1  energy,history,job-accomplishments  scott-surovell        State delegate   
2                      foreign-policy    barack-obama             President   
3                         health-care    blog-posting                   NaN   
4                        economy,jobs   charlie-crist                   NaN   

  state info  party  barely true counts  false counts  half true counts  \
0      Texas    1.0                   0             1                 0   
1   Virginia    0.0                   0             0                 1   
2   Illinois    0.0                  70            71               160   
3        NaN    0.5                   7            19                 3   
4    Florida    0.0                  15             9                20   

   mostly true counts  pants on fire counts                venue  lying ratio  \
0                   0                     0             a mailer     0.800000   
1                   1                     0      a floor speech.     0.300000   
2                 163                     9               Denver     0.432135   
3                   5                    44       a news release     0.841026   
4                  19                     2  an interview on CNN     0.461538   

   ratio significance  
0                0.01  
1                0.02  
2                1.00  
3                0.78  
4                0.65

# Subjects

In [11]:
def analyze(col):
    #takes in a column and spits out an analysis of the things in the counts of things in column
    total = []
    for s in col:
        if type(s) is not float:
            total += [i.strip().lower() for i in s.split(',')]
    c = Counter(total)
    most = c.most_common()
    return most

In [13]:
analyze(train.subject) #142 total

[('economy', 1163),
 ('health-care', 1129),
 ('taxes', 995),
 ('federal-budget', 744),
 ('education', 728),
 ('jobs', 712),
 ('state-budget', 696),
 ('candidates-biography', 653),
 ('elections', 607),
 ('immigration', 532),
 ('foreign-policy', 471),
 ('crime', 446),
 ('history', 405),
 ('energy', 382),
 ('legal-issues', 344),
 ('environment', 336),
 ('guns', 330),
 ('military', 315),
 ('job-accomplishments', 294),
 ('workers', 293),
 ('terrorism', 292),
 ('transportation', 269),
 ('message-machine-2012', 261),
 ('criminal-justice', 259),
 ('abortion', 255),
 ('state-finances', 245),
 ('states', 230),
 ('public-health', 225),
 ('women', 215),
 ('deficit', 214),
 ('pundits', 213),
 ('labor', 206),
 ('voting-record', 198),
 ('medicare', 195),
 ('congress', 195),
 ('corrections-and-updates', 194),
 ('children', 194),
 ('message-machine', 193),
 ('campaign-finance', 184),
 ('income', 179),
 ('poverty', 178),
 ('government-regulation', 174),
 ('stimulus', 172),
 ('ethics', 160),
 ('governmen

In [17]:
speaker = analyze(train.speaker) #142 total

In [23]:
speaker.index(('arne-duncan', 5))

344

In [214]:
def get_classes(col):
    return {i.strip().lower() for s in col for i in s.split(',')}
    
def get_list(col):
    total = [[] for i in range(len(col))]
    for idx, s in enumerate(col):
        if type(s) is float: #NaN
            continue
        features = [i.strip().lower() for i in s.split(',')]
        total[idx] = features
    return total

# def get_encoder(train):
#     #should only take in the processed data
#     enc = MultiLabelBinarizer()
#     enc.fit(train)
#     return enc

# def get_one_hot(X, enc):
#     return enc.transform(X)

In [1]:
glove['north carolina']

NameError: name 'glove' is not defined

In [219]:
list(get_classes(train.subject))

['city-government',
 'marijuana',
 'florida',
 'guns',
 'pensions',
 'disability',
 'diversity',
 'campaign-finance',
 'gays-and-lesbians',
 'privacy',
 'families',
 'state-budget',
 'fires',
 'wealth',
 'afghanistan',
 'china',
 'polls',
 'census',
 'corrections-and-updates',
 'iraq',
 'state-finances',
 'infrastructure',
 'sexuality',
 'population',
 'animals',
 'pop-culture',
 'transparency',
 'weather',
 'abortion',
 'crime',
 'islam',
 'autism',
 'agriculture',
 'message-machine',
 'food-safety',
 'congress',
 'debt',
 'financial-regulation',
 'retirement',
 'history',
 'bush-administration',
 'states',
 'labor',
 'immigration',
 'medicaid',
 'government-regulation',
 'housing',
 'debates',
 'recreation',
 'social-security',
 'voting-record',
 'consumer-safety',
 'baseball',
 'technology',
 'military',
 'gas-prices',
 'federal-budget',
 'bipartisanship',
 'supreme-court',
 'religion',
 'criminal-justice',
 'poverty',
 'children',
 'sports',
 'obama-birth-certificate',
 'public-ser

In [231]:
classes = list(get_classes(train.subject))
processed = get_list(train.subject)
enc = MultiLabelBinarizer(classes=classes)
train_output = enc.fit_transform(processed)
print(output)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [232]:
#lets try to do it for validation set now
p = get_list(valid.subject)
valid_output = enc.transform(p)

In [250]:
#for test set
p2 = get_list(test.subject)
test_output = enc.transform(p2)

/Users/mauriciow/miniconda3/envs/nlu/lib/python3.7/site-packages/sklearn/preprocessing/label.py:935: UserWarning: unknown class(es) ['nightlife', 'politifacts-top-promises'] will be ignored
  .format(sorted(unknown, key=str)))


In [251]:
p2[0]

['immigration']

In [258]:
len(classes)

142

In [254]:
test_output.shape

(1267, 142)

In [262]:
subj_train = get_subject_train()
classes = get_classes()

In [265]:
subj_train[0][28]

1

In [264]:
classes.index('abortion')

28

In [225]:
output[0]

1

In [212]:

# enc = get_encoder(processed)
# subject_train_onehot = get_one_hot(processed, enc)
# print(subject_train_onehot)

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [209]:
subject_onehot_train

I'm going to test both one hot encoding and glove embeddings

# Speaker
2910 of them, only 300 of them have more than 5 statements, and only 50 have more than 25 statements

In [69]:
most = analyze(train.speaker) 

# Job

So far, I've seen 1108 jobs. But some seem to be duplicates

'member of the u.s. house' and 'u.s. representative'

also, some are highly specific 
'u.s. representative, florida district 2'
could be interesting to test if we can jut remove everythign 

later idea: choose x amount (say 50) amount of the most common words in the set, that aren't fluff words, and strip out all the words that aren't in that set, 

anotehr idea: strip out everythign after the comma (e.g. 'ceo, apple inc', state senator, district 32)
another idea: a network to figure out what's important in the metadata

another idea: get BERT embeddings of job. And use those


In [139]:
# job = train["speaker's job"]

In [177]:
def parse_job():
    job = train["speaker's job"]
    total = []
    for i, j in enumerate(job):
        if type(j) is not float:
            total.append(j.strip().lower())
    c = Counter(total)
    most = c.most_common()
    return most

def _get_list(col):
    total = [[] for i in range(len(col))]
    for idx, s in enumerate(col):
        if type(s) is float: #NaN
            continue
        features = [i.strip().lower() for i in s.split(',')]
        total[idx] = features
    return total

def parse_job_commas():
    #throw away everything after second comma. 
    job = train["speaker's job"]
    total = []
    for i, j in enumerate(job):
        if type(j) is not float:
            first = j.split(',')[0].split('--')[0]
            total.append(first.strip().lower())
    c = Counter(total)
    most = c.most_common()
    return most

In [175]:
parse_job_commas()

[('u.s. senator', 742),
 ('president', 554),
 ('governor', 430),
 ('u.s. representative', 376),
 ('president-elect', 273),
 ('presidential candidate', 255),
 ('state senator', 239),
 ('state representative', 184),
 ('former governor', 177),
 ('senator', 149),
 ('milwaukee county executive', 149),
 ('u.s. house of representatives', 102),
 ('attorney', 102),
 ('congressman', 89),
 ('governor of new jersey', 78),
 ('social media posting', 78),
 ('co-host on cnn\'s "crossfire"', 73),
 ('u.s. congressman', 63),
 ('congresswoman', 53),
 ('speaker of the house of representatives', 50),
 ('lawyer', 50),
 ('businessman', 44),
 ('governor of ohio as of jan. 10', 43),
 ('author', 43),
 ('chairman', 42),
 ('lieutenant governor', 39),
 ('candidate for u.s. senate and physician', 39),
 ('political action committee', 37),
 ('radio host', 36),
 ('u.s. senator from ohio', 34),
 ('attorney general', 33),
 ('house majority leader', 33),
 ('mayor', 32),
 ('former president', 31),
 ('consultant', 31),
 ('c

In [178]:
len(parse_job_commas())

932

# Venue

there are nearly 4000 categories
We need some sort of generelization (hueristic of words)

I think actually the best heuristic might be get the noun phrase of the sentence
can also use simply BERT embeddings, and use drop-out. 

'a rally in columbus' --> rally

In [1]:
analyze(train.venue)

NameError: name 'analyze' is not defined